name: TheVinculumGroup
favicon: null
layout_spectrum: 0.2867384
typography_spectrum: 0.8870968
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e7e2a2'
    - '#835734'
    - '#a87c57'
    - '#5e2a12'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
