layout_spectrum: 0.5132598371710628
typography_spectrum: 0.9553770932834595
color:
  brandColors:
    - '#000000'
    - '#e7e2a2'
    - '#835734'
    - '#a87c57'
    - '#5e2a12'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 0.75
name: The Vinculum Group
favicon: null
title: www.The VinculumGroup.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
